# Chi-Square Test of Independence
# Berkeley Graduate Admissions Bias
# Are sex and status dependent?
# Data for largest six departments
# Last updated 10.24.2018 @ 11:00am
```{r}
library(dplyr)
# Load the dataset
Berkeley <- read.csv(file=url("https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Instructor/berkeley.csv"))
str(Berkeley)

A <- Berkeley %>%
  filter(department == "A")

sex    <- A$sex
status <- A$status

# Select the two variables we want to test and make a table
Observed <- table(sex,status)
print(Observed)


# What kind of table would we expect to see if Ho is true?

Expected <- outer(rowSums(Observed),colSums(Observed))/sum(Observed)

# Create a new function to compute the chi-squared test statistic
# The function's name is chisq, the required input is a data table 
# Obs(erved) is the observed data table; variables are defined later
# Exp(ected) is a contingency table computed from the Observed data
# Outer is the outer product of two vectors, which makes a matrix
# http://en.wikipedia.org/wiki/Outer_product

chisq.teststat <- function(Obs){ 
  Exp <- outer(rowSums(Obs),colSums(Obs))/sum(Obs)
  sum((Obs-Exp)^2/Exp)
}

obs.diff <- chisq.teststat(table(sex,status))

# Resampling permutation test loop and graph of results
# Start with selecting the two variables to be analyzed

N <- 10^4-1
random.diff<-numeric(N)

for (i in 1:N){
  STATUS.perm <-sample(status)
  RANDOM.table <- table(sex, STATUS.perm)
  random.diff[i]<-chisq.teststat(RANDOM.table)
}

# Graph the null distribution of the test statistic

hist(random.diff, prob=T,
     main="Null Distribution of Chi-Square Test Statistic",
     xlab="randomly generated chi-square statistics", 
     xlim=c(0,max(max(random.diff),obs.diff)),
     ylim=c(0,1))
abline(v=obs.diff,
       col="blue",
       lty=5)  

# Print the test statistic and p-value
# The p-value is (sum(random.diff >= obs.diff) + 1)/(N + 1) 
print(paste("The chi-square test statistic is ", round(obs.diff,4), ".", sep=""),quote=F)
print(paste("The p-value for the test of independence is ", format((sum(random.diff >= obs.diff) + 1)/(N + 1),scientific=F), ".", sep=""),quote=F)

table <- table(sex, status)
prop.table(table, 1)
```

```{r}
toy1 <- read.csv("https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Instructor/tommypickles1.csv")
toy2 <- read.csv("https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Instructor/tommypickles2.csv")

observed <- table(toy1$outcome)
prop.table(observed)
chisq.test(observed)

prob <- c(.4,.4,.2)
expected <- prob * 99
expected

observed <- table(toy2$outcome)
prop.table(observed)
chisq.test(observed, p=prob)
```